# Generated by Django 3.1 on 2020-08-10 16:42

import app_base.widgets
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0002_auto_20200810_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='test',
            field=app_base.widgets.IconPicker(max_length=100, null=True),
        ),
    ]
