# Generated by Django 3.1 on 2020-08-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0003_productlist_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
