# Generated by Django 3.1 on 2020-08-31 15:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_base', '0008_auto_20200831_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('customer_last_name', models.CharField(max_length=80)),
                ('customer_phone_number', models.CharField(max_length=12)),
                ('customer_postal_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')])),
                ('customer_national_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('\\b(?!(\\d)\\1{3})[13-9]{4}[1346-9][013-9]{5}\\b')])),
                ('customer_city', models.CharField(max_length=20)),
                ('customer_state', models.CharField(max_length=20)),
                ('customer_birth', django_jalali.db.models.jDateTimeField()),
                ('customer_address', models.CharField(max_length=200)),
                ('customer_extra_explanation', models.CharField(max_length=300, null=True)),
                ('purchase_method', models.CharField(choices=[(0, 'کارت اعتباری'), (1, 'نقدی')], max_length=20)),
                ('datetime', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='app_base.productmodel')),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-datetime',),
            },
        ),
    ]
