# Generated by Django 3.1 on 2020-08-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0010_auto_20200901_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factormodel',
            name='purchase_method',
            field=models.CharField(max_length=20),
        ),
    ]
