# Generated by Django 3.1 on 2020-08-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0011_auto_20200901_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factormodel',
            name='customer_national_code',
            field=models.CharField(max_length=10),
        ),
    ]
