# Generated by Django 3.1 on 2020-08-31 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0012_auto_20200901_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factormodel',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
