# Generated by Django 3.1 on 2020-09-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0013_auto_20200901_0421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factormodel',
            options={'ordering': ('-datetime',), 'verbose_name': 'پیش فاکتور', 'verbose_name_plural': 'پیش فاکتور ها'},
        ),
        migrations.RemoveField(
            model_name='factormodel',
            name='products',
        ),
    ]
