# Generated by Django 3.1 on 2020-09-02 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0014_auto_20200902_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='factor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_base.factormodel'),
        ),
    ]
