# Generated by Django 3.1 on 2020-09-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0018_auto_20200903_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factormodel',
            name='customer_address',
            field=models.CharField(max_length=200, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='factormodel',
            name='customer_birthdate',
            field=models.CharField(max_length=10, null=True, verbose_name='تاریخ تولد خریدار'),
        ),
        migrations.AlterField(
            model_name='factormodel',
            name='description',
            field=models.CharField(max_length=300, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='factormodel',
            name='purchase_method',
            field=models.CharField(max_length=20, verbose_name='نحوه تسویه حق العمل'),
        ),
    ]
