# Generated by Django 3.1 on 2020-09-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0019_auto_20200903_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='number',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد محصول'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ به ریال'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(choices=[(1, 'یخچال/فریزر (REF)'), (2, 'اجاق گاز (GC)'), (3, 'ماشین لباسشویی (WM)'), (4, 'تلویزیون (TV)'), (5, 'لوازم خانگی کوچک (SHA)'), (6, 'متفرقه (OTHER)'), (7, 'محصولات نوکار (BI)'), (8, 'ماشین ظرفشویی (DW)'), (9, 'تهویه هوا (AC)')], max_length=100, verbose_name='نام محصول'),
        ),
    ]
